In [1]:
import numpy as np
np

<module 'numpy' from '/home/issa/miniconda3/envs/mzc/lib/python3.12/site-packages/numpy/__init__.py'>

In [2]:
print(np.zeros(10))
print(np.ones(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
np.full(3, 9.9)

array([9.9, 9.9, 9.9])

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
np.arange(4)

array([0, 1, 2, 3])

In [6]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

In [8]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
n = np.array([
    [1,2],
    [3,4],
    [4,9],
    [8,7]
])

In [10]:
n[0][1]

np.int64(2)

In [11]:
n[0, 1]

np.int64(2)

In [12]:
n[:, 1] = [0,0,0,0]
n

array([[1, 0],
       [3, 0],
       [4, 0],
       [8, 0]])

In [13]:
n[:, 0]

array([1, 3, 4, 8])

In [14]:
# radnom number between 0 to 1 (uniform distribution)
np.random.seed(42)
np.random.rand(5, 2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [15]:
# normal distributin
np.random.seed(42)
np.random.randn(5, 2)

array([[ 0.49671415, -0.1382643 ],
       [ 0.64768854,  1.52302986],
       [-0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473],
       [-0.46947439,  0.54256004]])

In [16]:
np.random.seed(42)
np.random.randint(low=0, high=100, size=(4,2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86]])

In [17]:
a >= 3 

array([False, False,  True,  True])

In [18]:
a[ a >= 3]

array([3, 4])

In [19]:
a.min()

np.int64(1)

In [20]:
a.max()

np.int64(4)

In [21]:
a.sum()

np.int64(10)

In [22]:
a.mean()

np.float64(2.5)

In [23]:
a.std()

np.float64(1.118033988749895)

In [24]:
v = np.array([2, 4, 5, 6])
u = np.array([1, 0, 0, 2])

In [25]:
def vector_vector_multiplication(u, v):

    assert v.shape[0] == u.shape[0]

    result = 0.0
    for i in range(u.shape[0]):

        result += u[i] * v[i]

    return result

In [26]:
r = vector_vector_multiplication(u,v)
r

np.float64(14.0)

In [27]:
# or use:

u.dot(v)

np.int64(14)

In [38]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [39]:
U.shape

(3, 4)

In [42]:
def matrix_vector_multiplication(U, u):

    assert U.shape[1] == u.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], u)

    return result

In [43]:
matrix_vector_multiplication(U, u)

array([14.,  5.,  5.])

In [44]:
U.dot(u)

array([14,  5,  5])

In [53]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [54]:
V[:, 0]

array([1., 0., 0., 2.])

In [55]:
def matrix_matrix_multiplication(U, V):

    assert U.shape[1] == V.shape[0]

    result = np.zeros((U.shape[0], V.shape[1]))

    for i in range(V.shape[1]):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [56]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [62]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [63]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
# for inverse matrix
Vs = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1]
])

iVs = np.linalg.inv(Vs)

In [74]:
iVs

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [76]:
# matrix * mastrix(inverse) = identity matrix
iV.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])